refactor(devnet): better makefiles for docker ci builds

diff --git a/mithril-client-cli/Makefile b/mithril-client-cli/Makefile
--- a/mithril-client-cli/Makefile
+++ b/mithril-client-cli/Makefile
@@ -13,25 +13,6 @@ build:
 	${CARGO} build --release
 	cp ../target/release/mithril-client .
 
-build-ci:
-	# Check that we are on Linux, then build
-	if [ "$$(uname -s)" != "Linux" ]; then \
-		echo "Error: this target only supports Linux"; \
-		exit 1; \
-	fi; \
-	RAW_ARCH=$$(uname -m); \
-	if [ "$$RAW_ARCH" = "x86_64" ]; then \
-		ARCH="amd64"; \
-	elif [ "$$RAW_ARCH" = "aarch64" ]; then \
-		ARCH="arm64"; \
-	else \
-		echo "Error: unsupported architecture $$RAW_ARCH"; \
-		exit 1; \
-	fi; \
-	${CARGO} build --release; \
-	mkdir -p ./bin-linux-$${ARCH}; \
-	cp ../target/release/mithril-client ./bin-linux-$${ARCH}/mithril-client
-
 run: build
 	@./mithril-client $(call args,defaultstring)
 
@@ -58,7 +39,23 @@ doc:
 docker-build:
 	cd ../ && docker build -t mithril/mithril-client -f mithril-client-cli/Dockerfile .
 
-docker-build-ci: build-ci
+docker-build-ci: build
+	# Check that we are on Linux, then build
+	if [ "$$(uname -s)" != "Linux" ]; then \
+		echo "Error: this target only supports Linux"; \
+		exit 1; \
+	fi; \
+	RAW_ARCH=$$(uname -m); \
+	if [ "$$RAW_ARCH" = "x86_64" ]; then \
+		ARCH="amd64"; \
+	elif [ "$$RAW_ARCH" = "aarch64" ]; then \
+		ARCH="arm64"; \
+	else \
+		echo "Error: unsupported architecture $$RAW_ARCH"; \
+		exit 1; \
+	fi; \
+	mkdir -p ./bin-linux-$${ARCH}; \
+	cp ../target/release/mithril-client ./bin-linux-$${ARCH}/mithril-client
 	cd ../ && docker build -t mithril/mithril-client -f mithril-client-cli/Dockerfile.ci --build-arg DOCKER_IMAGE_FROM .
 
 docker-run:
