fix(devnet): Docker images creation with CI mode

diff --git a/mithril-aggregator/Makefile b/mithril-aggregator/Makefile
--- a/mithril-aggregator/Makefile
+++ b/mithril-aggregator/Makefile
@@ -8,6 +8,25 @@ build:
 	${CARGO} build --release
 	cp ../target/release/mithril-aggregator .
 
+build-ci:
+	# Check that we are on Linux, then build
+	if [ "$$(uname -s)" != "Linux" ]; then \
+		echo "Error: this target only supports Linux"; \
+		exit 1; \
+	fi; \
+	RAW_ARCH=$$(uname -m); \
+	if [ "$$RAW_ARCH" = "x86_64" ]; then \
+		ARCH="amd64"; \
+	elif [ "$$RAW_ARCH" = "aarch64" ]; then \
+		ARCH="arm64"; \
+	else \
+		echo "Error: unsupported architecture $$RAW_ARCH"; \
+		exit 1; \
+	fi; \
+	${CARGO} build --release; \
+	mkdir -p ./bin-linux-$${ARCH}; \
+	cp ../target/release/mithril-aggregator ./bin-linux-$${ARCH}/mithril-aggregator
+
 run: build
 	./mithril-aggregator serve
 
@@ -31,7 +50,7 @@ doc:
 docker-build:
 	cd ../ && docker build -t mithril/mithril-aggregator -f mithril-aggregator/Dockerfile .
 
-docker-build-ci: build
+docker-build-ci: build-ci
 	cd ../ && docker build -t mithril/mithril-aggregator -f mithril-aggregator/Dockerfile.ci --build-arg DOCKER_IMAGE_FROM --build-arg CARDANO_NODE_VERSION .
 
 docker-run:
diff --git a/mithril-signer/Makefile b/mithril-signer/Makefile
--- a/mithril-signer/Makefile
+++ b/mithril-signer/Makefile
@@ -11,6 +11,25 @@ build:
 run: build
 	./mithril-signer
 
+build-ci:
+	# Check that we are on Linux, then build
+	if [ "$$(uname -s)" != "Linux" ]; then \
+		echo "Error: this target only supports Linux"; \
+		exit 1; \
+	fi; \
+	RAW_ARCH=$$(uname -m); \
+	if [ "$$RAW_ARCH" = "x86_64" ]; then \
+		ARCH="amd64"; \
+	elif [ "$$RAW_ARCH" = "aarch64" ]; then \
+		ARCH="arm64"; \
+	else \
+		echo "Error: unsupported architecture $$RAW_ARCH"; \
+		exit 1; \
+	fi; \
+	${CARGO} build --release; \
+	mkdir -p ./bin-linux-$${ARCH}; \
+	cp ../target/release/mithril-signer ./bin-linux-$${ARCH}/mithril-signer
+
 debug:
 	${CARGO} run -- -vvv
 
@@ -31,7 +50,7 @@ doc:
 docker-build:
 	cd ../ && docker build -t mithril/mithril-signer -f mithril-signer/Dockerfile .
 
-docker-build-ci: build
+docker-build-ci: build-ci
 	cd ../ && docker build -t mithril/mithril-signer -f mithril-signer/Dockerfile.ci --build-arg DOCKER_IMAGE_FROM --build-arg CARDANO_NODE_VERSION .
 
 docker-run:
